# Server 服务端配置
server:
  port: 8081

spring:
  devtools: # 热部署生效
    restart:
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
    time-zone: GMT+8
  http:
    encoding:
      charset: UTF-8
      force: true
  aop:
    proxy-target-class: true
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 100MB

# 数据库连接
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/my_test_project?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=true&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

# JavaMailSender 邮件发送的配置
  mail:
    host: smtp.qq.com  #发送邮件服务器
    username: 604764332@qq.com #发送邮件的邮箱地址
    password: bclzwotkfeelbfaa #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    default-encoding: UTF-8
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    properties.mail.smtp.port: 465 #端口号465或587

#    properties:
#      mail:
#        debug: false


mybatis:
  mapper-locations: classpath:mapper/*.xml # xml路径
  type-aliases-package: com.test.mapper
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志

  # mapper通用配置
mapper:
  mappers: com.test.utils.mapper.MyMapper
  not-empty: false
  identity: MYSQL

#pagehelper
pagehelper:
  helperDialect:  mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

